# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'LearnApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LearnApp

pod 'Firebase/Core'
pod 'FirebaseDatabase'
pod 'Firebase/Auth'

end
